[versions]
agp = "8.12.1"
# Make sure that a KSP version aligned with project's Kotlin version
# https://developer.android.com/build/migrate-to-ksp#add-ksp
colorpickerCompose = "1.1.2"
hiltAndroid = "2.57.1"
hiltNavigationCompose = "1.2.0"
javaWebsocket = "1.5.7"
kotlin = "2.2.20"
kotlinxSerializationJson = "1.9.0"
ksp = "2.2.20-2.0.3" # "kotlinVersion-kspVersion"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
ktor = "3.1.0"
lifecycleRuntimeKtx = "2.9.0"
activityCompose = "1.10.1"
composeBom = "2025.09.00"
navigationCompose = "2.9.0"
leakcanaryAndroid = "3.0-alpha-8"
numberpicker = "1.0.3"
orgEclipsePahoMqttv5Client = "1.2.5"
orgEclipsePahoMqttv3Client = "1.2.5"
robolectric = "4.16"
mockitoKotlin = "5.4.0"
roomRuntime = "2.7.1"
coreKtxVersion = "1.6.1"
speedometerAndroid = "1.0.0-ALPHA02"
turbine = "1.2.0"
zxingCore = "3.5.2"
zxingAndroidEmbedded = "4.3.0"
datastorePreferences = "1.1.7"
accompanistPermissions = "0.36.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "roomRuntime" }
colorpicker-compose = { module = "com.github.skydoves:colorpicker-compose", version.ref = "colorpickerCompose" }
speedometer-android = { module = "com.github.anastr:speedometer-android", version.ref = "speedometerAndroid" }
zxing-core = { module = "com.google.zxing:core", version.ref = "zxingCore" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltAndroid" }
java-websocket = { module = "org.java-websocket:Java-WebSocket", version.ref = "javaWebsocket" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
ktor-network = { module = "io.ktor:ktor-network", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-client-core = {module = "io.ktor:ktor-client-core",version.ref = "ktor" }
ktor-client-io = {module = "io.ktor:ktor-client-cio",version.ref = "ktor" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanaryAndroid" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
numberpicker = { module = "com.chargemap.compose:numberpicker", version.ref = "numberpicker" }
org-eclipse-paho-mqttv5-client = { module = "org.eclipse.paho:org.eclipse.paho.mqttv5.client", version.ref = "orgEclipsePahoMqttv5Client" }
org-eclipse-paho-mqttv3-client = { module = "org.eclipse.paho:org.eclipse.paho.client.mqttv3", version.ref = "orgEclipsePahoMqttv3Client" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
core-ktx = { group = "androidx.test", name = "core-ktx", version.ref = "coreKtxVersion" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
zxing-android-embedded = { module = "com.journeyapps:zxing-android-embedded", version.ref = "zxingAndroidEmbedded" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = {id = "com.google.devtools.ksp", version.ref = "ksp"}
serializarion = {id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"}
hilt-android ={id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid"}
androidx-room = {id = "androidx.room", version.ref = "roomRuntime"}

